post_upgrade() {
  if findmnt --fstab -uno SOURCE /boot &>/dev/null && ! mountpoint -q /boot; then
    echo "WARNING: /boot appears to be a separate partition but is not mounted."
  fi
  if [ -e /boot/upstream/kernel8.img ] ; then
    # rpi5
    echo 'Updating rpi3/4/5 kernel image and dtb in upstream dir.'
    cp -f /boot/dtbs/broadcom/bcm2712-rpi-5-b.dtb      /boot/upstream/bcm2712-rpi-5-b.dtb
    cp -f /boot/dtbs/broadcom/bcm2711-rpi-4-b.dtb      /boot/upstream/bcm2711-rpi-4-b.dtb
    cp -f /boot/dtbs/broadcom/bcm2837-rpi-3-a-plus.dtb /boot/upstream/bcm2837-rpi-3-a-plus.dtb
    cp -f /boot/dtbs/broadcom/bcm2837-rpi-3-b-plus.dtb /boot/upstream/bcm2837-rpi-3-b-plus.dtb
    cp -f /boot/dtbs/broadcom/bcm2837-rpi-3-b.dtb      /boot/upstream/bcm2837-rpi-3-b.dtb
    cp -f /boot/Image /boot/upstream/kernel8.img
  elif [ -e /boot/upstream/bcm2711-rpi-4-b.dtb ] ; then
    # rpi3/4
    echo 'Updating rpi3/4 dtbs in upstream dir.'
    cp -f /boot/dtbs/broadcom/bcm2711-rpi-4-b.dtb      /boot/upstream/bcm2711-rpi-4-b.dtb
    cp -f /boot/dtbs/broadcom/bcm2837-rpi-3-a-plus.dtb /boot/upstream/bcm2837-rpi-3-a-plus.dtb
    cp -f /boot/dtbs/broadcom/bcm2837-rpi-3-b-plus.dtb /boot/upstream/bcm2837-rpi-3-b-plus.dtb
    cp -f /boot/dtbs/broadcom/bcm2837-rpi-3-b.dtb      /boot/upstream/bcm2837-rpi-3-b.dtb
  fi
}

post_remove() {
  rm -f boot/initramfs-linux.img
  rm -f boot/initramfs-linux-fallback.img
}
