GARNAME             = perl-HTTP-Message
GARVERSION          = 6.18
MASTER_SITES        = https://search.cpan.org/CPAN/authors/id/O/OA/OALDERS/
DEPENDS             = perl/perl-Encode-Locale

include ../../perl/perl/perl-module.mk
