GARNAME        = perl-HTML-Parser
GARVERSION     = 3.72
MASTER_SITES   = http://www.cpan.org/authors/id/G/GA/GAAS/
DEPENDS        = perl/perl-HTML-Tagset
PERL_MODULE_SO = true

include ../../perl/perl/perl-module.mk
