
GARNAME      = bootfiles-h618.orangepi_zero3
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = h618
mm_U-BOOT_BOARD_TYPE      = board-h618.orangepi_zero3
mm_U-BOOT_BOARD_DEFCONFIG = orangepi_zero3_defconfig

include ../bootloader/install-board-bootloader-aw.mk
