#
# to compile, run:
# ./complie.sh
#
#

dtb_file="amlogic/meson-sm1-x96-air.dtb"

# uncomment to apply extra DT overlays. This is list overlays separated by white space
# dtb_overlays="amlogic/overlay/<overlay1>.dtbo amlogic/overlay/<overlay2>.dtbo"

# uncomment to have quite boot with bootsplash screen
# quiet_boot="yes"

# uncomment to add any extra params to kernel boot cmd. line
# extra_params="drm.edid_firmware=edid/s2-tek.bin"

early_con="earlycon console=ttyAML0,115200n8"

nfs_top_dir="mm2-nfs-networkboot-latest"
ram_top_dir="mm2-ram-networkboot-latest"


