GARNAME      = perl-DateTime-TimeZone
GARVERSION   = 2.47
MASTER_SITES = https://www.cpan.org/CPAN/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-Class-Load perl/perl-Class-Singleton perl/perl-Params-Validate

include ../../perl/perl/perl-module.mk
