#!/bin/sh

. /etc/conf

# 'vt02' starts X on virtual terminal 2.
# '-logverbose 6' enables useful troubleshooting output in /var/log/Xorg.0.0.log.
exec /usr/bin/X :0.0 vt02 -logverbose 6 -verbose 0 > /dev/null 2>&1
