GARNAME      = perl-PerlMagick
GARVERSION   = 6.89
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/J/JC/JCRISTY/
#SOURCEFILES  = PerlMagick-6.89

DEPENDS = /lib/ImageMagick

include ../../perl/perl/perl-module.mk
