
GARNAME      = bootfiles-h616.tanix_tx6s
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = h616
mm_U-BOOT_BOARD_TYPE      = board-h616.tanix_tx6s
mm_U-BOOT_BOARD_DEFCONFIG = tanix_tx6s_defconfig

include ../bootloader/install-board-bootloader-aw.mk
