
GARNAME      = bootfiles-rk3566.urve-pi
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

SOC_TYPE                  = rk3566
mm_U-BOOT_BOARD_TYPE      = board-rk3566.urve-pi
mm_U-BOOT_BOARD_DEFCONFIG = rock-3c-rk3566_defconfig

include ../bootloader/install-board-bootloader-rk.mk
