
GARNAME      = bootfiles-board-sm1.x96_air2g
GARVERSION   = 2026-05-29
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

export SOC_TYPE                  = sm1
export mm_U-BOOT_BOARD_TYPE      = board-sm1.x96_air2g
export mm_U-BOOT_BOARD_DEFCONFIG = x96_air_defconfig
export FIP_BOARD                 = x96-air

include ../bootloader/install-board-bootloader-aml.mk
