
GARNAME      = bootfiles-rk3566.orangepi-3b
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

SOC_TYPE                  = rk3566
mm_U-BOOT_BOARD_TYPE      = board-rk3566.orangepi_3b
mm_U-BOOT_BOARD_DEFCONFIG = orangepi-3b-rk3566_defconfig

include ../bootloader/install-board-bootloader-rk.mk
