LABEL MiniMyth2

  LINUX /Image
  FDT /dtbs/amlogic/meson-sm1-x96-air.dtb

  # Cmd line to production-like quiet boot
  # APPEND root=/dev/mmcblk0p2 rw rootwait earlycon console=ttyAML0,115200n8 logo.nologo vt.cur_default=1
  # Cmd line to debug kernel boot
  APPEND root=/dev/mmcblk0p2 rw rootwait earlycon console=ttyAML0,115200n8 debug MM_DEBUG="yes"
