GARNAME      = perl-Date-Manip
GARVERSION   = 6.85
MASTER_SITES = http://www.cpan.org/authors/id/S/SB/SBECK/
DEPENDS      = perl/perl-libwww-perl perl/perl-XML-DOM perl/perl-XML-Parser

include ../../perl/perl/perl-module.mk
