GARNAME      = perl-Date-Manip
GARVERSION   = 6.53
MASTER_SITES = http://www.cpan.org/authors/id/S/SB/SBECK/
DEPENDS      = perl/perl-libwww-perl perl/perl-XML-DOM perl/perl-XML-Parser
#http://search.cpan.org/CPAN/authors/id/S/SB/SBECK/Date-Manip-${pkgver}.tar.gz
include ../../perl/perl/perl-module.mk
