
GARNAME      = bootfiles-h6.beelink_gs1
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = h6
mm_U-BOOT_BOARD_TYPE      = board-h6.beelink_gs1
mm_U-BOOT_BOARD_DEFCONFIG = beelink_gs1_defconfig
CRUST_CONFIG              = beelink_gs1_defconfig

include ../bootloader/install-board-bootloader-aw.mk

