LABEL MiniMyth2

  LINUX /Image
  FDT /dtbs/amlogic/meson-s4-s905y4-khadas-vim1s.dtb

  # Cmd line to production-like quiet boot
  # APPEND root=/dev/mmcblk0p2 rw rootwait earlycon=meson,0xfe07a000 console=ttyS0,921600n8 no_console_suspend consoleblank=0 bootargs2=8250.nr_uarts=0 clk_ignore_unused pd_ignore_unused cma=384M logo.nologo vt.cur_default=1
  # Cmd line to debug kernel boot
  APPEND root=/dev/mmcblk0p2 rw rootwait earlycon=meson,0xfe07a000 console=ttyS0,921600n8 no_console_suspend consoleblank=0 bootargs2=8250.nr_uarts=0 clk_ignore_unused pd_ignore_unused cma=384M debug MM_DEBUG="yes"
