
GARNAME      = bootfiles-rk3399.orangepi_4_lts
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               extlinux.conf \
               minimyth.conf   \

SOC_TYPE                  = rk3399
mm_U-BOOT_BOARD_TYPE      = board-rk3399.orangepi_4_lts
mm_U-BOOT_BOARD_DEFCONFIG = rock-pi-4-rk3399_defconfig

include ../bootloader/install-board-bootloader-rk.mk
