GARNAME           = perl-Test-Fatal
GARVERSION        = 0.014
MASTER_SITES      = https://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/
DEPENDS           = perl/perl-Try-Tiny

include ../../perl/perl/perl-module.mk
