GARNAME      = perl-DateTime-Format-Builder
GARVERSION   = 0.80
MASTER_SITES = http://www.cpan.org/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-Class-Factory-Util perl/perl-DateTime perl/perl-DateTime-Format-Strptime perl/perl-Params-Validate perl/perl-Task-Weaken

include ../../perl/perl/perl-module.mk
