
title      MiniMyth2
version    7.0.11
sort-key   MiniMyth2
options    root=/dev/mmcblk0p2 console=ttyMSM0,115200n8 rw rootwait earlycon clk_ignore_unused pd_ignore_unused consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 debug _MM_DEBUG="yes" deferred_probe_timeout=0
linux      /Image
devicetree /dtbs/qcom/sc8280xp-radxa-dragon-q8b.dtb
