
title      MiniMyth2
version    6.18
sort-key   MiniMyth2
options    root=/dev/mmcblk1p2 console=ttyMSM0,115200n8 rw rootwait earlycon consoleblank=0 console=tty1 debug
linux      /Image
devicetree /dtbs/qcom/sc8280xp-radxa-dragon-q8b.dtb
