GARNAME      = perl-DateTime-Locale
GARVERSION   = 0.45
MASTER_SITES = http://www.cpan.org/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-List-MoreUtils perl/perl-Params-Validate

include ../../perl/perl/perl-module.mk
