
GARNAME      = perl-Perl-Strip
GARVERSION   = 1.1
MASTER_SITES = https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/
DEPENDS      = perl/perl-common-sense perl/perl-PPI

include ../../perl/perl/perl-module.mk
