GARNAME      = libwww-perl
GARVERSION   = 6.15
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/
DEPENDS      = perl/perl-HTML-Parser perl/perl-URI perl/perl-HTTP-Date

include ../../perl/perl/perl-module.mk

CONFIGURE_ARGS += -n

CONFIGURE_ENV := echo N | $(CONFIGURE_ENV)
