
GARNAME      = bootfiles-board-s905d3.vim3l
GARVERSION   = 2026-05-23
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

export SOC_TYPE                  = sm1
export mm_U-BOOT_BOARD_TYPE      = board-s905d3.vim3l
export mm_U-BOOT_BOARD_DEFCONFIG = khadas-vim3l_defconfig
export FIP_BOARD                 = khadas-vim3l

include ../bootloader/install-board-bootloader-aml.mk
