#!/bin/sh

device=''

cmdline=`/bin/cat /proc/cmdline`
/bin/echo " ${cmdline} " | /bin/grep -q -i ' MM_MINIMYTH_BOOT_DEVICE=' 2> /dev/null
if /usr/bin/test $? -eq 0 ; then
    device=`/bin/echo " ${cmdline} " | /bin/sed -e 's%^.* MM_MINIMYTH_BOOT_DEVICE="\?\([^ "]*\)"\? .*$%\1%'`
fi

if /usr/bin/test -z ${device} ; then
    device='/dev/disk/by-label/minimyth'
fi

for devlink in ${DEVLINKS} ; do
    if /usr/bin/test "${devlink}" = "${device}" ; then
        exit 0
    fi
done

exit 1
