/usr/lib/perl5/*/CGI/
/usr/lib/perl5/*/CGI.pm
/usr/lib/perl5/*/CPAN/
/usr/lib/perl5/*/CPAN.pm
/usr/lib/perl5/*/CPANPLUS/
/usr/lib/perl5/*/CPANPLUS.pm
/usr/lib/perl5/*/Devel/
/usr/lib/perl5/*/ExtUtils/
/usr/lib/perl5/*/pod/
/usr/lib/perl5/*/Pod/
/usr/lib/perl5/*/Term/
/usr/lib/perl5/*/Test/
/usr/lib/perl5/*/*/CORE/
/usr/lib/perl5/*/*/Devel/
/usr/lib/perl5/*/*/auto/Devel/
/usr/lib/perl5/*/*/auto/DynaLoader/DynaLoader.a
