
GARNAME      = bootfiles-h728.x96q_pro_plus
GARVERSION   = 2026-09-05
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = a523
mm_U-BOOT_BOARD_TYPE      = board-h728.x96q_pro_plus
mm_U-BOOT_BOARD_DEFCONFIG = x96q_pro_plus_defconfig

include ../bootloader/install-board-bootloader-aw.mk
