
GARNAME      = bootfiles-rk3328.beelink_a1
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               extlinux.conf \
               minimyth.conf   \

SOC_TYPE                  = rk3328
mm_U-BOOT_BOARD_TYPE      = board-rk3328.beelink_a1
mm_U-BOOT_BOARD_DEFCONFIG = beelink-a1-rk3328_defconfig

include ../bootloader/install-board-bootloader-rk.mk
