GARNAME           = perl-TimeDate
GARVERSION        = 1.20
MASTER_SITES      = http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/
DEPENDS           = perl/perl-Carp-Clan
BUILDDEPS         = perl/perl-Test-Exception

include ../../perl/perl/perl-module.mk
