
GARNAME      = kickstart-oe
GARVERSION   = 2.7.3
CATEGORIES   = utils
MASTER_SITES = http://git.yoctoproject.org/cgit/cgit.cgi/poky/snapshot/
DISTFILES    = \
	poky-yocto-$(GARVERSION).tar.gz \
	h313-generic.conf \
	h313-generic.wks \
	h6-generic.conf \
	h6-generic.wks \
	h616-generic.conf \
	h616-generic.wks \
	h618-generic.conf \
	h618-generic.wks \
	a523-generic.conf \
	a523-generic.wks \
	rk3328-generic.conf \
	rk3328-generic.wks \
	rk3399-generic.conf \
	rk3399-generic.wks \
	rk3528-generic.conf \
	rk3528-generic.wks \
	rk3566-generic.conf \
	rk3566-generic.wks \
	rk3568-generic.conf \
	rk3568-generic.wks \
	rk3588-generic.conf \
	rk3588-generic.wks \
	rk3588s-generic.conf \
	rk3588s-generic.wks \
	board-h313.tanix_tx1.conf   \
	board-h313.tanix_tx1.wks   \
	board-h313.tanix_tx1_v1.2.conf \
	board-h313.tanix_tx1_v1.2.wks \
	board-rpi2.conf             \
	board-rpi2.wks              \
	board-rpi3.mainline32.conf  \
	board-rpi3.mainline32.wks   \
	board-rpi3.mainline64.conf  \
	board-rpi3.mainline64.wks   \
	board-rpi3.rpi32.conf       \
	board-rpi3.rpi32.wks        \
	board-rpi4.mainline64.conf  \
	board-rpi4.mainline64.wks   \
	board-rpi5.mainline64.conf  \
	board-rpi5.mainline64.wks   \
	board-rpi34.mainline64.conf \
	board-rpi34.mainline64.wks  \
	board-rpi345.mainline64.conf \
	board-rpi345.mainline64.wks \
	board-rpi4.rpi32.conf       \
	board-rpi4.rpi32.wks        \
	board-rpi4.rpi64.conf       \
	board-rpi4.rpi64.wks        \
	board-rpi5.rpi64.conf       \
	board-rpi5.rpi64.wks        \
	board-s905.conf             \
	board-s905.wks              \
	board-s912.conf             \
	board-s912.wks              \
	board-sm1.x96_air2g.conf    \
	board-sm1.x96_air2g.wks     \
	board-sm1.tanix_tx5_plus.conf \
	board-sm1.tanix_tx5_plus.wks \
	board-g12.radxa_zero.conf    \
	board-g12.radxa_zero.wks     \
	board-x86pc.bios.conf       \
	board-x86pc.bios.wks        \
	board-x86pc.efi64.conf      \
	board-x86pc.efi64.wks       \
	board-x86pc.bios_efi64.conf \
	board-x86pc.bios_efi64.wks  \
	default-mbr.wks             \
	default-gpt.wks             \
	create-image.sh             \

# Allwinner H6 boards
H6_BOARDS_LIST= \
	board-h6.beelink_gs1   \
	board-h6.eachlink_mini \
	board-h6.tanix_tx6     \
	board-h6.tanix_tx6_mini \
	board-h6.orangepi_3    \
	board-h6.orangepi_3_lts \

# Allwinner H313 boards
H313_BOARDS_LIST= \
	board-h313.x96_q         \
	board-h313.x96_q_v5.1    \
	board-h313.x96_q_lpddr3  \
	board-h313.x96_q_lpddr3_v1.3 \

# Allwinner H616 boards
H616_BOARDS_LIST= \
	board-h616.orangepi_zero2    \
	board-h616.tanix_tx6s        \
	board-h616.tanix_tx6s_lpddr3 \
	board-h616.tanix_tx6s_axp313 \
	board-h616.t95               \
	board-h616.x96_mate          \
	board-h616.pendoo_x12pro     \

# Allwinner H616 boards
H618_BOARDS_LIST= \
	board-h618.orangepi_zero3    \
	board-h618.vontar_h618       \
	board-h618.transpeed-8k618-t \
	board-h618.orangepi_zero2w   \

# Allwinner H618 boards
A523_BOARDS_LIST= \
	board-h728.x96q_pro_plus \
	board-t527.orangepi_4a \
	board-a527.cubie_a5e   \

# Rockchip RK3328 boards
RK3328_BOARDS_LIST = \
	board-rk3328.beelink_a1 \

# Rockchip RK3399 boards
RK3399_BOARDS_LIST = \
	board-rk3399.rockpi4-b  \
	board-rk3399.rockpi4-se \
	board-rk3399.orangepi_4 \
	board-rk3399.orangepi_4_lts \

# Rockchip RK3528 boards
RK3528_BOARDS_LIST = \
	board-rk3528.vontar_r3  \
	board-rk3528.rock2-a    \

# Rockchip RK3566 boards
RK3566_BOARDS_LIST = \
	board-rk3566.x96_x6     \
	board-rk3566.urve-pi    \
	board-rk3566.quartz64-b \
	board-rk3566.zero3e    \
	board-rk3566.zero3w    \
	board-rk3566.rock3-c   \
	board-rk3566.orangepi_3b \

# Rockchip RK3568 boards
RK3568_BOARDS_LIST = \
	board-rk3568.rock3-a   \
	board-rk3568.rock3-b   \

# Rockchip RK3588 boards
RK3588_BOARDS_LIST = \
	board-rk3588.rock5-b   \
	board-rk3588.rock5-itx \
	board-rk3588.orangepi_5_plus \
	board-rk3588.nanopc_t6 \
	board-rk3588.nanopc_t6_lts \
	board-rk3588.rock5-t   \

# Rockchip RK3588 boards
RK3588S_BOARDS_LIST = \
	board-rk3588s.rock5-a  \
	board-rk3588s.rock5-c  \
	board-rk3588s.nanopi_m6 \
	board-rk3588s.orangepi_5 \
	board-rk3588s.orangepi_5_pro \
	board-rk3588s.nanopi_r6s \

PATCHFILES  = poky-yocto-2.7.3-bitbake-skip-python2-checks.patch
PATCHFILES += poky-yocto-2.7.3-add-biosplusefi-image-plugin.patch
PATCHFILES += poky-yocto-2.7.3-add-copy-mm2-files-into-image-boot-part.patch
PATCHFILES += poky-yocto-2.7.3-make-PARTUUID-as-constant-0x346d1a6a.patch
PATCHFILES += backport-001-wic-Add--offset-argument-for-partitions.patch
PATCHFILES += backport-002-wic-Fix--extra-space-argument-handling.patch
PATCHFILES += backport-003-wic-Fix-error-message-when-reporting-invalid-offset.patch
PATCHFILES += backport-004-wic-Add-512-Byte-alignment-to--offset.patch
PATCHFILES += poky-yocto-2.7.3-allow-arbitral-part-start-sector.patch
PATCHFILES += poky-yocto-2.7.3-fix-running-on-python3.11.patch

WORKSRC = $(WORKDIR)/poky-yocto-$(GARVERSION)
LICENSE = GPL2

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	utils/diffstat \
	disk/dosfstools \
	disk/mtools \
	disk/e2fsprogs \
	disk/gptfdisk \
	utils/pseudo \
	disk/parted \
	bootloaders/syslinux \
	bootloaders/grub2 \
	python3/python \
	python3/python-codegen \
	python3/python-ply \
	python3/python-beautifulsoup4 \
	python3/python-simplediff \

CONFIGURE_SCRIPTS = 
BUILD_SCRIPTS     = 
INSTALL_SCRIPTS   = kickstart h6_boards h313_boards h616_boards h618_boards a523_boards rk3328_boards rk3399_boards rk3528_boards rk3566_boards rk3568_boards rk3588s_boards rk3588_boards

include ../../gar.mk

COPY_FILES = \
	for file in $(strip $(1)) ; do \
	    echo "installing .conf/.wks for $${file} ..." ; \
	    cp -f $(WORKDIR)/$(strip $(2)).conf $(DESTDIR)$(bindir)/kickstart/conf/multiconfig/$${file}.conf ; \
	    cp -f $(WORKDIR)/$(strip $(2)).wks $(DESTDIR)$(bindir)/kickstart/$${file}.wks ; \
	done ; \

install-h6_boards:
	@$(call COPY_FILES, $(H6_BOARDS_LIST), h6-generic)

install-h313_boards:
	@$(call COPY_FILES, $(H313_BOARDS_LIST), h313-generic)

install-h616_boards:
	@$(call COPY_FILES, $(H616_BOARDS_LIST), h616-generic)

install-h618_boards:
	@$(call COPY_FILES, $(H618_BOARDS_LIST), h618-generic)

install-a523_boards:
	@$(call COPY_FILES, $(A523_BOARDS_LIST), a523-generic)

install-rk3328_boards:
	@$(call COPY_FILES, $(RK3328_BOARDS_LIST), rk3328-generic)

install-rk3399_boards:
	@$(call COPY_FILES, $(RK3399_BOARDS_LIST), rk3399-generic)

install-rk3528_boards:
	@$(call COPY_FILES, $(RK3528_BOARDS_LIST), rk3528-generic)

install-rk3566_boards:
	@$(call COPY_FILES, $(RK3566_BOARDS_LIST), rk3566-generic)

install-rk3568_boards:
	@$(call COPY_FILES, $(RK3568_BOARDS_LIST), rk3568-generic)

install-rk3588s_boards:
	@$(call COPY_FILES, $(RK3588S_BOARDS_LIST), rk3588s-generic)

install-rk3588_boards:
	@$(call COPY_FILES, $(RK3588_BOARDS_LIST), rk3588-generic)

install-kickstart:
	@mkdir -p $(DESTDIR)$(bindir)/kickstart/bitbake
	@mkdir -p $(DESTDIR)$(bindir)/kickstart/cache
	@mkdir -p $(DESTDIR)$(bindir)/kickstart/classes
	@mkdir -p $(DESTDIR)$(bindir)/kickstart/conf
	@mkdir -p $(DESTDIR)$(bindir)/kickstart/conf/multiconfig
	@mkdir -p $(DESTDIR)$(bindir)/kickstart/scripts
	@#
	@cp -rf $(WORKSRC)/bitbake/bin $(DESTDIR)$(bindir)/kickstart/bitbake/
	@cp -rf $(WORKSRC)/bitbake/lib $(DESTDIR)$(bindir)/kickstart/bitbake/
	@cp -rf $(WORKSRC)/meta/lib/oe $(DESTDIR)$(bindir)/kickstart/bitbake/lib/
	@#
	@cp -f $(WORKSRC)/meta/classes/base.bbclass          $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/logging.bbclass       $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/metadata_scm.bbclass  $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/mirrors.bbclass       $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/patch.bbclass         $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/sanity.bbclass        $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/staging.bbclass       $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/terminal.bbclass      $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/utility-tasks.bbclass $(DESTDIR)$(bindir)/kickstart/classes/
	@cp -f $(WORKSRC)/meta/classes/utils.bbclass         $(DESTDIR)$(bindir)/kickstart/classes/
	@#
	@cp -f $(WORKSRC)/meta/conf/abi_version.conf         $(DESTDIR)$(bindir)/kickstart/conf/
	@cp -f $(WORKSRC)/meta/conf/bitbake.conf             $(DESTDIR)$(bindir)/kickstart/conf/
	@cp -f $(WORKSRC)/meta/conf/sanity.conf              $(DESTDIR)$(bindir)/kickstart/conf/
	@cp -f $(WORKSRC)/meta/conf/multiconfig/default.conf $(DESTDIR)$(bindir)/kickstart/conf/multiconfig/
	@#
	@cp -rf $(WORKSRC)/scripts/lib/     $(DESTDIR)$(bindir)/kickstart/scripts/lib/
	@cp -f  $(WORKSRC)/scripts/wic      $(DESTDIR)$(bindir)/kickstart/scripts/wic
	@#
	@cp -f $(WORKDIR)/create-image.sh   $(DESTDIR)$(bindir)/kickstart/
	@#
	@cp -f $(WORKDIR)/board-*.conf      $(DESTDIR)$(bindir)/kickstart/conf/multiconfig/
	@cp -f $(WORKDIR)/board-*.wks       $(DESTDIR)$(bindir)/kickstart/
	@#
	@cp -f $(WORKDIR)/default-mbr.wks   $(DESTDIR)$(bindir)/kickstart/default-mbr.wks
	@cp -f $(WORKDIR)/default-gpt.wks   $(DESTDIR)$(bindir)/kickstart/default-gpt.wks
	@#
	@# Remove all host tools requirements as we are listing them in BUILDEPS
	@sed -i -e "s/HOSTTOOLS +=/__HOSTTOOLS +=/g" $(DESTDIR)$(bindir)/kickstart/conf/bitbake.conf
	@echo 'HOSTTOOLS += " "' >> $(DESTDIR)$(bindir)/kickstart/conf/bitbake.conf
	@$(MAKECOOKIE)

clean-all: clean
	@rm -rf $(DESTDIR)$(bindir)/kickstart*
	@$(MAKECOOKIE)
