GARNAME           = perl-Class-Load
GARVERSION        = 0.06
MASTER_SITES      = http://www.cpan.org/authors/id/S/SA/SARTAK/
DEPENDS           = perl/perl-Module-Install

include ../../perl/perl/perl-module.mk
