GARNAME      = perl-Module-Implementation
GARVERSION   = 0.09
MASTER_SITES = http://www.cpan.org/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-Module-Runtime perl/perl-Try-Tiny

include ../../perl/perl/perl-module.mk
