
GARNAME      = perl-PPI
GARVERSION   = 1.270
MASTER_SITES = https://cpan.metacpan.org/authors/id/M/MI/MITHALDU/
DEPENDS      = perl/perl-Params-Util perl/perl-Clone perl/perl-IO-string

include ../../perl/perl/perl-module.mk
