
GARNAME      = bootfiles-rk3588s.nanopi_m6
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf

SOC_TYPE                  = rk3588s
mm_U-BOOT_BOARD_TYPE      = board-rk3588s.nanopi_m6
mm_U-BOOT_BOARD_DEFCONFIG = nanopi-m6-rk3588s_defconfig

include ../bootloader/install-board-bootloader-rk.mk
