GARNAME             = perl-List-MoreUtils
GARVERSION          = 0.25_02
MASTER_SITES        = http://www.cpan.org/authors/id/V/VP/VPARSEVAL/
PERL_MODULE_PATCHES = gar.patch
PERL_MODULE_SO      = true
DEPENDS             =

include ../../perl/perl/perl-module.mk
