GARNAME             = perl-List-MoreUtils
GARVERSION          = 0.428
MASTER_SITES        = https://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/
PERL_MODULE_SO      = true
DEPENDS             =

include ../../perl/perl/perl-module.mk
