#!/bin/sh
################################################################################
# acpi
################################################################################
. /etc/rc.d/functions

start() {

    /bin/echo ${MM_ACPI_VIDEO_FLAGS} > /proc/sys/kernel/acpi_video_flags

    case "${MM_ACPI_EVENT_BUTTON_POWER}" in
        off)
            /bin/sed -e 's%@MM_ACPI_EVENT_BUTTON_POWER@%/sbin/poweroff%'    -i /etc/acpi/events/power
            ;;
        sleep)
            /bin/sed -e 's%@MM_ACPI_EVENT_BUTTON_POWER@%/usr/bin/mm_sleep%' -i /etc/acpi/events/power
            ;;
    esac

    mm_message_output info "starting ACPI ..."

    /usr/sbin/acpid

    return 0
}

stop() {
    mm_message_output info "stopping ACPI ..."

    /usr/bin/test -n "`/bin/pidof acpid`" && /usr/bin/killall acpid

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
