#!/bin/sh
################################################################################
# cache_pruner
################################################################################
. /etc/rc.d/functions

start() {

    if [ ! "x${MM_MYTHTV_CACHE_FOR_PRUNE}" = "xno" ] ; then

        if [ -z `/bin/pidof mm_mythtv_cache_pruner` ] ; then

            /usr/bin/mm_mythtv_cache_pruner &
            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/cache_pruner] Launching mm_mythtv_cache_pruner ..."
        fi
    fi

    this_script_done
}

stop() {

    if [ -n "`/bin/pidof mm_mythtv_cache_pruner`" ] ; then

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/cache_pruner] Killing mm_mythtv_cache_pruner daemon ..."
        /usr/bin/killall -9 mm_mythtv_cache_pruner > /dev/null 2>&1
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
