#!/bin/sh
################################################################################
# chrome
################################################################################
. /etc/rc.d/functions

start() {
    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/chrome] Starting..."

    if /usr/bin/test "x${MM_NETFLIX_ENABLED}" = "xyes" ; then

        mm_confrw_get google-chrome-config.tar.bz2 /home/minimyth/google-chrome-config.tar.bz2
        if /usr/bin/test ! -e /home/minimyth/google-chrome-config.tar.bz2 ; then
            /usr/bin/logger -t minimyth -p "local0.err" "[init.d/chrome] can't download chrome state archive (google-chrome-config.tar.bz2)..."
            return 1
        else
            /bin/rm -rf /home/minimyth/.config*
            bunzip2 -dc /home/minimyth/google-chrome-config.tar.bz2 | tar -xf - -C /home/minimyth
            /bin/rm -f /home/minimyth/google-chrome-config.tar.bz2
            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/chrome] chrome state sucessfuly restored..."
        fi

    fi

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/chrome] Started with return code=0..."

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
