#!/bin/sh
################################################################################
# defaults
#
# This script configures default setting in db at first run
################################################################################
. /etc/rc.d/functions

start() {

    # Making default settngs in DB
    first_run_done=`mm_mythdb_settings_get 'MiniMyth2FirstRunDone'`

    if [ "x${first_run_done}" = "x1" ] ; then

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Not initial run - settings seems to be already defaulted..."

    else

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Initial run - will defaulting some settings..."

        mm_mythdb_settings_set 'MiniMyth2FirstRunDone' '1'

        if [ ! "x${MM_LIRC_FETCH_LIRCRC}" = "xyes" ] ; then

            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Initial run with build-in lircrc file - will defaulting major MythTV jumppoints..."

            mm_mythdb_jumppoints_update 'Main Menu'              'Alt+h'
            mm_mythdb_jumppoints_update 'Program Guide'          'Alt+e'
            mm_mythdb_jumppoints_update 'Program Finder'         'Alt+f'
            mm_mythdb_jumppoints_update 'TV Recording Playback'  'Alt+r'
            mm_mythdb_jumppoints_update 'Live TV'                'Alt+t'
            mm_mythdb_jumppoints_update 'Status Screen'          'Alt+i'
            mm_mythdb_jumppoints_update 'MythGallery'            'Alt+p'
            mm_mythdb_jumppoints_update 'MythGame'               'Alt+g'
            mm_mythdb_jumppoints_update 'Play music'             'Alt+m'
            mm_mythdb_jumppoints_update 'MythNews'               'Alt+n'
            mm_mythdb_jumppoints_update 'Video Default'          'Alt+v'
            mm_mythdb_jumppoints_update 'Play radio stream'      'Alt+s'
            mm_mythdb_jumppoints_update 'MythWeather'            'Alt+w'
            mm_mythdb_jumppoints_update 'ZoneMinder Events'      'Alt+z'
            mm_mythdb_jumppoints_update 'MythNetSearch'          'Alt+a'
            mm_mythdb_jumppoints_update 'Standby Mode'           'Alt+b'
        fi

        # Making default keybindings
        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting critical MythTV keybindings..."
        mm_mythdb_keybindings_update "Main Menu"                   "EXIT"                 "Ctrl+Esc"
        mm_mythdb_keybindings_update "Main Menu"                   "EXITPROMPT"           ""
        mm_mythdb_keybindings_update "Main Menu"                   "STANDBYMODE"          "F22"
        # This seems to be required for right arrow doing listepisodes...
        mm_mythdb_keybindings_update "TV Frontend"                 "LISTRECORDEDEPISODES" "W"
        # Adding F23/F24 as keybindings for CEC TV-on/off
        mm_mythdb_keybindings_update "Global"                      "TVPOWERON"  "F23"
        mm_mythdb_keybindings_update "Global"                      "TVPOWEROFF" "F24"

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting critical MythTV user settings..."
        mm_mythdb_settings_update    'NetworkControlEnabled'       '1'
        mm_mythdb_settings_update    'OverrideExitMenu'            '6'
        mm_mythdb_settings_update    'HideMouseCursor'             '1'
        mm_mythdb_settings_update    'FrontendIdleTimeout'         '10'

        mm_mythdb_settings_set       'HaltCommand'                 'poweroff'
        mm_mythdb_settings_set       'RebootCommand'               'reboot'

        mm_mythdb_settings_set       'AudioOutputDevice'           'ALSA:default'

        # Set OSD fonts.
        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting OSD fonts..."
        mm_mythdb_settings_update    'OSDFont'                     'FreeSans.ttf'
        mm_mythdb_settings_update    'OSDCCFont'                   'FreeSans.ttf'

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting convienience MythTV user settings..."
        mm_mythdb_settings_set       'PlaybackBoxStartInTitle'     '0'
        mm_mythdb_settings_set       'PlayBoxEpisodeSort'          'Season'
        mm_mythdb_settings_set       'PlayBoxOrdering'             '1'
        mm_mythdb_settings_set       'QueryInitialFilter'          '1'
        mm_mythdb_settings_set       'UseProgStartMark'            '1'
        mm_mythdb_settings_set       'UseVideoModes'               '1'

    fi

    this_script_done
}

stop() {

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
