#!/bin/sh
################################################################################
# defaults
#
# This script configures default setting in db at first run
################################################################################
. /etc/rc.d/functions

start() {

    # Making default settngs in DB
    first_run_done=`mm_mythdb_settings_get 'MiniMyth2FirstRunDone'`

    if [ "x${first_run_done}" = "x1" ] ; then

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Not initial run - settings seems to be already defaulted..."

    else

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Initial run - will defaulting some settings..."

        if [ ! "x${MM_LIRC_FETCH_LIRCRC}" = "xyes" ] ; then

            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Initial run with build-in lircrc file - will defaulting major MythTV jumppoints..."

            mm_mythdb_jumppoints_update 'Main Menu'              'Alt+h'
            mm_mythdb_jumppoints_update 'Program Guide'          'Alt+e'
            mm_mythdb_jumppoints_update 'Program Finder'         'Alt+f'
            mm_mythdb_jumppoints_update 'TV Recording Playback'  'Alt+r'
            mm_mythdb_jumppoints_update 'Live TV'                'Alt+t'
            mm_mythdb_jumppoints_update 'Status Screen'          'Alt+i'
            mm_mythdb_jumppoints_update 'MythGallery'            'Alt+p'
            mm_mythdb_jumppoints_update 'MythGame'               'Alt+g'
            mm_mythdb_jumppoints_update 'Play music'             'Alt+m'
            mm_mythdb_jumppoints_update 'MythNews'               'Alt+n'
            mm_mythdb_jumppoints_update 'Video Default'          'Alt+v'
            mm_mythdb_jumppoints_update 'Play radio stream'      'Alt+s'
            mm_mythdb_jumppoints_update 'MythWeather'            'Alt+w'
            mm_mythdb_jumppoints_update 'ZoneMinder Events'      'Alt+z'
            mm_mythdb_jumppoints_update 'MythNetSearch'          'Alt+a'
            mm_mythdb_jumppoints_update 'Standby Mode'           'Alt+b'
        fi

        case "${MM_X_HW_TYPE}" in
                nvidia_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Nvidia HW Accell. detected: initial set DefaultVideoPlaybackProfile to \"VDPAU Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    ;;
                nvidia_legacy_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Nvidia legacy HW Accell. detected: initial set DefaultVideoPlaybackProfile to \"VDPAU Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    ;;
                nouveau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Nouveau HW Accell. detected: initial set DefaultVideoPlaybackProfile to \"VDPAU Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    ;;
                radeon_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Radeon HW Accell. detected: initial set DefaultVideoPlaybackProfile to \"VDPAU Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    ;;
                radeon_vaapi)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Radeon HW Accell. detected: initial set DefaultVideoPlaybackProfile to \"VAAPI Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VAAPI Normal"
                    ;;
                intel_vaapi)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Intel HW Accell. detected: initial set DefaultVideoPlaybackProfile to \"VAAPI Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VAAPI Normal"
                    ;;
                vmware)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] VMware detected: initial set DefaultVideoPlaybackProfile to \"OpenGL Slim\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "OpenGL Slim"
                    ;;
                armsoc)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] ArmSOC detected: initial set DefaultVideoPlaybackProfile to \"V4L2 Codecs\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "V4L2 Codecs"
                    ;;
                meson)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Amlogic detected: initial set DefaultVideoPlaybackProfile to \"V4L2 Codecs\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "V4L2 Codecs"
                    ;;
                vc4)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Raspbery PI detected: initial set DefaultVideoPlaybackProfile to \"V4L2 Codecs\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "V4L2 Codecs"
                    ;;
                rockchip)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] RockChip detected: initial set DefaultVideoPlaybackProfile to \"V4L2 Codecs\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "V4L2 Codecs"
                    ;;
                sun4i)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] AllWinner detected: initial set DefaultVideoPlaybackProfile to \"V4L2 Codecs\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "V4L2 Codecs"
                    ;;
                *)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Unknown video HW: initial set DefaultVideoPlaybackProfile to \"OpenGL Slim\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "OpenGL Slim"
                    ;;
        esac

        # Making initial GUI and TV playback resolution as 1920x1080 as MythTV's default 640x480 seems problematic on some TV's...
        initial_resolution="1920x1080"
        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting TV playback resolution to ${initial_resolution} ..."
        # GUI part below is commented as alternative solution is implemented by patching mythtv code (see patch 114)
        # mm_mythdb_settings_set       "GuiVidModeResolution"       "${initial_resolution}"
        mm_mythdb_settings_set       "TVVidModeResolution"        "${initial_resolution}"

        # Making default keybindings
        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting critical MythTV keybindings..."
        mm_mythdb_keybindings_update "Main Menu"                   "EXIT"                 "Ctrl+Esc"
        mm_mythdb_keybindings_update "Main Menu"                   "EXITPROMPT"           ""
        mm_mythdb_keybindings_update "Main Menu"                   "STANDBYMODE"          "F22"
        # This seems to be required for right arrow doing listepisodes...
        mm_mythdb_keybindings_update "TV Frontend"                 "LISTRECORDEDEPISODES" "W"
        # Adding F23/F24 as keybindings for CEC TV-on/off
        mm_mythdb_keybindings_update "Global"                      "TVPOWERON"  "F23"
        mm_mythdb_keybindings_update "Global"                      "TVPOWEROFF" "F24"

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting critical MythTV user settings..."
        mm_mythdb_settings_update    'NetworkControlEnabled'       '1'
        mm_mythdb_settings_update    'OverrideExitMenu'            '6'
        mm_mythdb_settings_update    'HideMouseCursor'             '1'
        mm_mythdb_settings_update    'FrontendIdleTimeout'         '10'

        mm_mythdb_settings_set       'HaltCommand'                 'poweroff'
        mm_mythdb_settings_set       'RebootCommand'               'reboot'

        mm_mythdb_settings_set       'AudioOutputDevice'           'ALSA:default'

        # Set OSD fonts.
        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting OSD fonts..."
        mm_mythdb_settings_update    'OSDFont'                     'FreeSans.ttf'
        mm_mythdb_settings_update    'OSDCCFont'                   'FreeSans.ttf'

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/defaults] Defaulting convienience MythTV user settings..."
        mm_mythdb_settings_set       'PlaybackBoxStartInTitle'     '0'
        mm_mythdb_settings_set       'PlayBoxEpisodeSort'          'Season'
        mm_mythdb_settings_set       'PlayBoxOrdering'             '1'
        mm_mythdb_settings_set       'QueryInitialFilter'          '1'
        mm_mythdb_settings_set       'UseProgStartMark'            '1'
        mm_mythdb_settings_set       'UseVideoModes'               '1'

    fi

    mm_mythdb_settings_set 'MiniMyth2FirstRunDone' '1'

    this_script_done
}

stop() {

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
