#!/bin/sh
################################################################################
# extras
#
# This script (downloads and) mounts the extras directory tree.
################################################################################
. /etc/rc.d/functions

start() {

    if /usr/bin/test -n "${MM_EXTRAS_URL}" ; then
        if /usr/bin/test ! "${MM_EXTRAS_URL}" = "auto" && \
           /usr/bin/test ! "${MM_EXTRAS_URL}" = "global" ; then
            mm_message_output info "installing extras ..."
            /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/extras] Mounting Extras dir from ${MM_EXTRAS_URL}"
            mm_url_mount "${MM_EXTRAS_URL}" "@EXTRAS_ROOTDIR@"
            /sbin/ldconfig
        fi
    fi
    return 0
}

stop() {

    /bin/umount "${MM_EXTRAS_URL}"
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
