#!/bin/sh
################################################################################
# font
################################################################################
. /etc/rc.d/functions

start() {

    /bin/touch /var/init/font.inprogress

    local font

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/font] Starting..."

    if [ -n "${MM_FONT_FILE_TTF_DELETE}" ] || [ -n "${MM_FONT_FILE_TTF_ADD}" ] ; then

        if [ -n "${MM_FONT_FILE_TTF_DELETE}" ] ; then

            for font in ${MM_FONT_FILE_TTF_DELETE} ; do
                /bin/rm -f /usr/share/fonts/X11/TTF/${font}
                /bin/rm -f /usr/share/mythtv/fonts/${font}
            done

        fi

        cd /usr/share/fonts/X11/TTF
        /usr/bin/mkfontscale
        /usr/bin/mkfontdir

    fi

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/font] Started with return code=0..."

    /bin/rm -f /var/init/font.inprogress
    return 0
}

stop() {

    return 0

}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
