#!/bin/sh
################################################################################
# font
################################################################################
. /etc/rc.d/functions

start() {
    local font

    mm_message_output info "updating fonts ..."

    if /usr/bin/test -n "${MM_FONT_FILE_TTF_DELETE}" || /usr/bin/test -n "${MM_FONT_FILE_TTF_ADD}" ; then
        /bin/mkdir -p /usr/share/fonts/X11/TTF
        /bin/mkdir -p /usr/share/mythtv
        if /usr/bin/test -n "${MM_FONT_FILE_TTF_DELETE}" ; then
            for font in ${MM_FONT_FILE_TTF_DELETE} ; do
                /bin/rm -f /usr/share/fonts/X11/TTF/${font}
                /bin/rm -f /usr/share/mythtv/${font}
            done
        fi
        if /usr/bin/test -n "${MM_FONT_FILE_TTF_ADD}" ; then
            for font in ${MM_FONT_FILE_TTF_ADD} ; do
                /bin/rm -f /usr/share/mythtv/${font}
                if /usr/bin/test -e /usr/share/fonts/X11/TTF/${font} ; then
                    /bin/ln -sf /usr/share/fonts/X11/TTF/${font} /usr/share/mythtv/${font}
                fi
            done
        fi
        cd /usr/share/fonts/X11/TTF
        /usr/bin/mkfontscale
        /usr/bin/mkfontdir
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
