#!/bin/sh
################################################################################
# halt
################################################################################
. /etc/rc.d/functions

start() {
    # halt.
    if /usr/bin/test -f /halt ; then
        mm_message_output info "halting system ..."
        /sbin/halt -i
    # poweroff.
    else
        mm_message_output info "powering off system ..."
        /sbin/halt -i -p
    fi

    return 0
}

stop() {
    start

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
