#!/bin/sh
################################################################################
# halt
################################################################################
. /etc/rc.d/functions

start() {

    if [ -f /halt ] ; then

        mm_message_output info "halting system ..."
        /sbin/halt -i

    else

        mm_message_output info "turning-off system ..."
        /sbin/halt -i -p

    fi

    this_script_done
}

stop() {

    start

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
