#!/bin/sh
################################################################################
# housekeep
################################################################################
. /etc/rc.d/functions

start() {

    echo "--Scripts launcher-----------------------------------------------------" > /var/log/init.log
    grep "init.d/rc" /var/log/messages >> /var/log/init.log
    echo " " >> /var/log/init.log
    echo " " >> /var/log/init.log
    echo "--Scripts ret.codes----------------------------------------------------" >> /var/log/init.log
    grep "init.d"    /var/log/messages >> /var/log/init.log >> /var/log/init.log

    /bin/sleep 10
    cp /etc/conf.d/minimyth /var/log/settings

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/housekeep] Gathering system-info..."
    /usr/bin/mm_getsysinfo

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/housekeep] Started with return code=0..."

    this_script_done
}

stop() {

    mm_message_output info "stopping housekeep ..."

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
