#!/bin/sh
################################################################################
# housekeep
################################################################################
. /etc/rc.d/functions

start() {

    /bin/sleep 10
    cp /etc/conf.d/minimyth /var/log/settings

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/housekeep] Gathering system-info..."
    /usr/bin/mm_getsysinfo

    this_script_done

    echo "--Scripts launcher-----------------------------------------------------" > /var/log/init.log
    grep "init.d/rc" /var/log/messages >> /var/log/init.log
    echo " " >> /var/log/init.log
    echo " " >> /var/log/init.log
    echo "--Scripts ret.codes----------------------------------------------------" >> /var/log/init.log
    grep "init.d"    /var/log/messages >> /var/log/init.log
    echo "--Scripts exec.durations-----------------------------------------------" >> /var/log/init.log

    cat /var/log/init-script-durations.log >> /var/log/init.log
}

stop() {

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
