#!/bin/sh
################################################################################
# kmsvnc
################################################################################
. /etc/rc.d/functions

start() {

    if [ "x${MM_VNC_ENABLED}" = "xkmsvnc" ] ; then

        if [ -z `/bin/pidof kmsvnc` ] ; then

            /usr/bin/kmsvnc --bind 0.0.0.0 --port 5900 --disable-ipv6 &
            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/kmsvnc] Launching kmsvnc daemon ..."
        fi
    fi

    this_script_done
}

stop() {

    if [ -n "`/bin/pidof kmsvnc`" ] ; then

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/kmsvnc] Killing kmsvnc daemon ..."
        /usr/bin/killall -9 kmsvnc > /dev/null 2>&1
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
