#!/bin/sh
################################################################################
# ld
################################################################################
. /etc/rc.d/functions

start() {

    mm_message_output info "configuring shared libraries ..."

    /sbin/ldconfig

    this_script_done

}

stop() {

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
