#!/bin/sh
################################################################################
# modules_manual
################################################################################
. /etc/rc.d/functions

start() {

    local kernel_module

    mm_message_output info "loading kernel modules (manual) ..."

    # Load hardware based kernel modules that are not auto-detected.
    for kernel_module in ${MM_HARDWARE_KERNEL_MODULES} ; do
        if ! /sbin/modprobe ${kernel_module} > /dev/null 2>&1 ; then
            mm_message_output warn "warning: failed to load kernel module: ${kernel_module}"
        fi
    done

    # MythPhone uses OSS not ALSA.
    if /usr/bin/test "${MM_PLUGIN_PHONE_ENABLED}" = "yes" ; then
        kernel_module='snd-pcm-oss'
        if ! /sbin/modprobe ${kernel_module} > /dev/null 2>&1 ; then
            mm_message_output warn "warning: failed to load kernel module: ${kernel_module}"
        fi
    fi

    return 0
}

stop() {

    mm_message_output info "unloading kernel modules (manual) ..."

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
