#!/bin/sh
################################################################################
# mythdb_buffer_create
#
# This script creates a buffer for accessing the MythTV database.
################################################################################
. /etc/rc.d/functions

start() {

    mm_mythdb_buffer_delete

    this_script_done
}

stop() {

    return 0

}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
