#!/bin/sh
################################################################################
# reboot
################################################################################
. /etc/rc.d/functions

start() {

    mm_message_output info "rebooting system ..."

    /sbin/reboot -i

    this_script_done
}

stop() {

    start

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
