#!/bin/sh
################################################################################
# reboot
################################################################################
. /etc/rc.d/functions

start() {

    mm_message_output info "rebooting system ..."

    /bin/touch /var/init/reboot.inprogress

    /sbin/reboot -i

    /bin/rm -f /var/init/reboot.inprogress
    return 0
}

stop() {

    start

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
