#!/bin/sh
################################################################################
# sensors
################################################################################
. /etc/rc.d/functions

start() {

    local kernel_module

    mm_message_output info "checking sensors ..."

    if ! /usr/bin/sensors > /dev/null 2>&1 ; then
       /usr/bin/logger -t minimyth -p "local0.warn" "[init.d/snsors] it is likely that the motherboard sensor chip was not detected."
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
