#!/bin/sh
################################################################################
# sleep
################################################################################
. /etc/rc.d/functions

start() {

    /bin/touch /var/init/sleep.inprogress

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/sleep] Started with return code=0..."

    idle_time=`mm_mythdb_settings_get "FrontendIdleTimeout"`
    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/sleep] FrontendIdleTimeout for this FE is:${idle_time}"

    if [ "x${idle_time}" = "x0" ] ; then

        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/sleep] Sleep on FrontendIdle disabled ..."

    else

        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/sleep] Launching in background  mm_sleep_on_standby ..."
        mm_sleep_on_standby &
    fi

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/sleep] Started with return code=0..."

    /bin/rm -f /var/init/sleep.inprogress
    return 0

}

stop() {

    if [ -n "`/bin/pidof mm_sleep_on_standby`" ] ; then

        /usr/bin/logger -t minimyth -p "local0.info" "[init.d/sleep] Killing mm_sleep_on_standby script..."
        /usr/bin/killall -9 mm_sleep_on_standby

    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
