#!/bin/sh
################################################################################
# splash
################################################################################
. /etc/rc.d/functions

start() {

    local DEPTH
    local GEOMETRY
    local LOGLEVEL
    local PRINTK
    local SPLASH_ENABLE
    local VXRES
    local VYRES
    local XRES
    local YRES

    mm_message_output info "starting splash screen ..."

    mm_splash_init()

    return 0
}

stop() {
    mm_message_output info 'stopping splash screen ...'

    mb_splash_halt()

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
