#!/bin/sh
################################################################################
# swap
################################################################################
. /etc/rc.d/functions

start() {

    /bin/touch /var/init/swap.inprogress

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/swap] Starting..."

    if [ "x${MM_SWAP_ENABLED}" = "xyes" ] ; then

        /usr/bin/zram-swap start
        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/swap] Started with return code=$? ..."

    else
        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/swap] Started with return code=0 ..."
    fi

    /bin/rm -f /var/init/swap.inprogress
    return 0
}

stop() {

    if [ "x${MM_SWAP_ENABLED}" = "xyes" ] ; then

        /usr/bin/zram-swap stop
        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/swap] Stopped with return code=0..."

    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
