#!/bin/sh
################################################################################
# swap
################################################################################
. /etc/rc.d/functions

start() {

    if [ "x${MM_SWAP_ENABLED}" = "xyes" ] ; then

        # swap_dev=`blkid | grep "TYPE=\"swap\" PARTLABEL=\"SWAP\"" | cut -d" " -f1 | sed -e "s/://g"`
        swap_dev=`blkid -L SWAP`
        if [ ! -z ${swap_dev} ] ; then
            /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/swap] creating swap on ${swap_dev} ..."
            /sbin/mkswap ${swap_dev}
            /sbin/swapon ${swap_dev}
        fi
        /usr/bin/zram-swap start
        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/swap] zram-swap returned code=$? ..."
    fi

    this_script_done
}

stop() {

    if [ "x${MM_SWAP_ENABLED}" = "xyes" ] ; then

        /usr/bin/zram-swap stop
        /sbin/swapoff -a
        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/swap] Stopped with return code=0..."

    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
