#!/bin/sh
################################################################################
# telnet
################################################################################
. /etc/rc.d/functions

start() {

    if [ ! -n "`/bin/pidof telnetd`" ] ; then

        /usr/sbin/telnetd
    fi

    this_script_done
}

stop() {

    if [ -n "`/bin/pidof telnetd`" ] ; then
        mm_message_output info "stopping telnet server ..."
        /usr/bin/killall telnetd
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
