#!/bin/sh
################################################################################
# telnet
################################################################################
. /etc/rc.d/functions

start() {

    /bin/touch /var/init/telnet.inprogress

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/telnet] Starting..."

    if [ ! -n "`/bin/pidof telnetd`" ] ; then

        /usr/sbin/telnetd
    fi

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/telnet] Started with return code=0..."

    /bin/rm -f /var/init/telnet.inprogress
    return 0

}

stop() {

    if [ -n "`/bin/pidof telnetd`" ] ; then
        mm_message_output info "stopping telnet server ..."
        /usr/bin/killall telnetd
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
