#!/bin/sh
################################################################################
# userleds
################################################################################
. /etc/rc.d/functions

start() {

    leds_list=$(find /sys/class/leds/*/trigger -type f 2>/dev/null)
    for led_trigger in ${leds_list} ; do
        led=$(echo ${led_trigger} | sed -e 's|\/sys\/class\/leds\/||g' -e 's|\/trigger||g' -e 's|\n||g')
        leds=${leds}"[${led}] "
    done

    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/userleds] Avaliable LEDs: ${leds}"

    # example: MM_USER_LED_TRIGGER="blue_led:trigger:netdev,blue_led:device_name:wlan0,blue_led:link:1,red_led:trigger:mmc0"

    if [ ! -z ${MM_USER_LED_TRIGGER} ] ; then

        triggers_list=$(echo ${MM_USER_LED_TRIGGER} | sed -e 's|,| |g')

        for trigger in ${triggers_list} ; do

              led_name=$(echo ${trigger} | cut -d":" -f1)
              led_attr=$(echo ${trigger} | cut -d":" -f2)
            attr_value=$(echo ${trigger} | cut -d":" -f3)

            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/userleds] setting [${attr_value}>/sys/class/leds/${led_name}/${led_attr}] ..."

            echo ${attr_value} > /sys/class/leds/${led_name}/${led_attr}
        done

    fi

    this_script_done
}

stop() {

    return 0

}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac
