#!/bin/sh
################################################################################
# video
#
# The script configures the video.
################################################################################
. /etc/rc.d/functions

start() {

    local hostname

    /bin/touch /var/lib/init/video.inprogress

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/video] Starting..."

    #Set MythTV video playback profile (if enabled by MM_VIDEO_PLAYBACK_PROFILE="auto")
    if [ -n "${MM_VIDEO_PLAYBACK_PROFILE}" ] ; then

        if [ "${MM_VIDEO_PLAYBACK_PROFILE}" = "auto" ] ; then

            case "${MM_X_HW_TYPE}" in
                nvidia_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] HW Accell. Nvidia detected, auto-switching DefaultVideoPlaybackProfile to \"VDPAU Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Switching ThemePainter to 'auto'"
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                nvidia_legacy_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] HW Accell. Nvidia legacy detected, auto-switching DefaultVideoPlaybackProfile to \"VDPAU Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Switching ThemePainter to 'auto'"
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                radeon_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] HW Accell. Radeon detected, auto-switching DefaultVideoPlaybackProfile to \"VDPAU Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Switching ThemePainter to 'auto'"
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                intel_vaapi)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] HW Accell Intel detected, auto-switching DefaultVideoPlaybackProfile to \"VAAPI Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VAAPI Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Switching ThemePainter to 'auto'"
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                vmware)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] VMware detected, auto-switching DefaultVideoPlaybackProfile to \"Slim\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "Slim"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Switching ThemePainter to 'auto'"
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                openmax)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Raspbery PI detected, auto-switching DefaultVideoPlaybackProfile to \"OpenMAX Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "OpenMAX Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Switching ThemePainter to 'qt'"
                    mm_mythdb_settings_set ThemePainter 'qt'
                    ;;
                *)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Non HW Accell Nvidia/Intel/ATI video detected, auto-switching DefaultVideoPlaybackProfile to \"Normal\""
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "Normal"
                    ;;
            esac

        else

            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] DefaultVideoPlaybackProfile forced by minimyth.conf to \"${MM_VIDEO_PLAYBACK_PROFILE}\""
            mm_mythdb_settings_set DefaultVideoPlaybackProfile "${MM_VIDEO_PLAYBACK_PROFILE}"

        fi

    else

        main_menu_jumppoint=`mm_mythdb_jumppoints_get 'Main Menu'`

        if [ "x${main_menu_jumppoint}" = "xAlt+h" ] ; then

            /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] DefaultVideoPlaybackProfile will be not touched..."

        else

            case "${MM_X_HW_TYPE}" in
                nvidia_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial setting DefaultVideoPlaybackProfile to \"VDPAU Normal\" as it is first run..."
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial switching ThemePainter to \"auto\" as it is first run..."
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                nvidia_legacy_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial setting DefaultVideoPlaybackProfile to \"VDPAU Normal\" as it is first run..."
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial switching ThemePainter to \"auto\" as it is first run..."
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                radeon_vdpau)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial setting DefaultVideoPlaybackProfile to  \"VDPAU Normal\" as it is first run..."
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VDPAU Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial switching ThemePainter to \"auto\" as it is first run..."
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                intel_vaapi)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial setting DefaultVideoPlaybackProfile to  \"VAAPI Normal\" as it is first run..."
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "VAAPI Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial switching ThemePainter to \"auto\" as it is first run..."
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                vmware)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial setting DefaultVideoPlaybackProfile to  \"Slim\" as it is first run..."
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "Slim"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial switching ThemePainter to \"auto\" as it is first run..."
                    mm_mythdb_settings_set ThemePainter 'auto'
                    ;;
                openmax)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial setting DefaultVideoPlaybackProfile to  \"OpenMAX Normal\" as it is first run..."
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "OpenMAX Normal"
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial switching ThemePainter to \"qt\" as it is first run..."
                    mm_mythdb_settings_set ThemePainter 'qt'
                    ;;
                *)
                    /usr/bin/logger -t minimyth -p "local0.info" "[init.d/video] Initial setting DefaultVideoPlaybackProfile to  \"Normal\" as it is first run..."
                    mm_mythdb_settings_set DefaultVideoPlaybackProfile "Normal"
                    ;;
            esac

        fi

    fi

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/video] Started with return code=0..."

    /bin/rm -f /var/lib/init/video.inprogress

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
