#!/bin/sh
################################################################################
# web
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info "starting web server ..."

    /bin/chown -Rh root:httpd /srv/www

    # Web page.
    /usr/sbin/lighttpd -f /etc/lighttpd-web.conf

    # Allow web access to the file system on machines that have security disabled.
    # It is run as root in order to provide access to all files.
    if /usr/bin/test "${MM_SECURITY_ENABLED}" = "no" ; then
        /usr/sbin/lighttpd -f /etc/lighttpd-dir.conf
    fi

    return 0
}

stop() {
    mm_message_output info "stopping web server ..."

    /usr/bin/test -n "`/bin/pidof lighttpd`" && /usr/bin/killall lighttpd

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
