#!/bin/sh
################################################################################
# weston
################################################################################
. /etc/rc.d/functions

start() {

    /bin/touch /var/init/weston.inprogress

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/weston] Starting..."

    # export XDG_RUNTIME_DIR=/var/run/xdg/minimyth
    weston -v > /var/log/weston.log &

    /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/weston] Started with return code=0..."

    /bin/rm -f /var/init/weston.inprogress
    return 0

}

stop() {

    mm_message_output info "stopping weston server ..."

    if [ -n "`/bin/pidof weston`" ] ; then
        /usr/bin/killall weston
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
