#!/bin/sh
################################################################################
# wiimote
################################################################################
. /etc/rc.d/functions

start() {

    local config
    local device
    local device_configured
    local devices

    if /usr/bin/test "${MM_WIIMOTE_ENABLED}" = "yes" ; then

        mm_message_output info 'starting bluetooth ...'

        devices=`cd /sys/class/bluetooth ; ls -1`
        if /usr/bin/test -z "${devices}" ; then
            mm_message_output err "error: no bluetooth device found."
            exit 1
        fi

        device_configured=0
        for device in ${devices} ; do
            if /usr/sbin/hciconfig ${device} up > /dev/null 2>&1 ; then
                device_configured=1
            else
                mm_message_output warn "warning: configuration of bluetooth device '${device}' failed."
            fi
        done
        if /usr/bin/test "${device_configured}" -eq 0 ; then
            mm_message_output err "error: no bluetooth device configured."
            exit 1
        fi

        mm_message_output info 'starting wminput ...'

        # wminput is already running, so return.
        if /usr/bin/test -n "`/bin/pidof wminput`" ; then
            return
        fi

        # Start
        if ! /sbin/modprobe uinput > /dev/null 2>&1 ; then
            mm_message_output err "error: failed to load kernel module: uinput"
            exit 1
        fi

        if /usr/bin/test -z "${MM_WIIMOTE_ADDRESS_0}" &&
           /usr/bin/test -z "${MM_WIIMOTE_ADDRESS_1}" &&
           /usr/bin/test -z "${MM_WIIMOTE_ADDRESS_2}" &&
           /usr/bin/test -z "${MM_WIIMOTE_ADDRESS_3}" ; then
            config=''
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default \
                && config='/etc/cwiid/wminput/default'
            if /usr/bin/test -z "${config}" ; then
                mm_message_output err "error: no 'wminput' config file found."
                exit 1
            fi
            if ! /usr/bin/wminput -d -c ${config} > /dev/null 2>&1 ; then
                mm_message_output err "error: failed to start 'wminput'."
                exit 1
            fi
        fi
        if /usr/bin/test -n "${MM_WIIMOTE_ADDRESS_0}" ; then
            config=''
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default_0 \
                && config='/etc/cwiid/wminput/default_0'
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default \
                && config='/etc/cwiid/wminput/default'
            if /usr/bin/test -z "${config}" ; then
                mm_message_output err "error: no 'wminput' config file found."
                exit 1
            fi
            /usr/bin/wminput -d -c ${config} ${MM_WIIMOTE_ADDRESS_0} > /dev/null 2>&1 &
        fi
        if /usr/bin/test -n "${MM_WIIMOTE_ADDRESS_1}" ; then
            config=''
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default_1 \
                && config='/etc/cwiid/wminput/default_1'
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default \
                && config='/etc/cwiid/wminput/default'
            if /usr/bin/test -z "${config}" ; then
                mm_message_output err "error: no 'wminput' config file found."
                exit 1
            fi
            /usr/bin/wminput -d -c ${config} ${MM_WIIMOTE_ADDRESS_1} > /dev/null 2>&1 &
        fi
        if /usr/bin/test -n "${MM_WIIMOTE_ADDRESS_2}" ; then
            config=''
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default_2 \
                && config='/etc/cwiid/wminput/default_2'
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default \
                && config='/etc/cwiid/wminput/default'
            if /usr/bin/test -z "${config}" ; then
                mm_message_output err "error: no 'wminput' config file found."
                exit 1
            fi
            /usr/bin/wminput -d -c ${config} ${MM_WIIMOTE_ADDRESS_2} > /dev/null 2>&1 &
        fi
        if /usr/bin/test -n "${MM_WIIMOTE_ADDRESS_3}" ; then
            config=''
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default_3 \
                && config='/etc/cwiid/wminput/default_3'
            /usr/bin/test -z "${config}" \
                && /usr/bin/test -e /etc/cwiid/wminput/default \
                && config='/etc/cwiid/wminput/default'
            if /usr/bin/test -z "${config}" ; then
                mm_message_output err "error: no 'wminput' config file found."
                exit 1
            fi
            /usr/bin/wminput -d -c ${config} ${MM_WIIMOTE_ADDRESS_3} > /dev/null 2>&1 &
        fi
    fi

    return 0
}


stop() {

    if /usr/bin/test -n "`/bin/pidof wminput`" ; then
        mm_message_output info 'stopping wminput ...'

        /usr/bin/killall wminput
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
