post_upgrade() {
	pacman --config=/etc/pacman.conf --noconfirm -S openssl 2>/dev/null
	if [ ! -e /usr/lib/libcrypto.so.1.1.1 ] ; then
		echo "running hack for libcrypto.so.1.1 issue"
		rm -f /usr/lib/libcrypto.so.1.1
		ldconfig 2>/dev/null
	fi
	if [ ! -e /usr/lib/libssl.so.1.1.1 ] ; then
		echo "running hack for missing libssl.so.1.1 issue"
		rm -f /usr/lib/libssl.so.1.1
		ldconfig 2>/dev/null
	fi
}

post_install() {
	post_upgrade
}

post_remove() {
	true
}
