
GARNAME      = bootfiles-rk3588s.orangepi_5
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf

SOC_TYPE                  = rk3588s
mm_U-BOOT_BOARD_TYPE      = board-rk3588s.orangepi_5

# uncomment and set this for dedicated defconfig.
# if commented out, generic defconfig 'generic-<soc>_defconfig' will be used...
# mm_U-BOOT_BOARD_DEFCONFIG =

include ../bootloader/install-board-bootloader-rk.mk
