GARNAME           = perl-Date-Calc
GARVERSION        = 6.3
MASTER_SITES      = http://search.cpan.org/CPAN/authors/id/S/ST/STBEY/
# PERL_MODULE_STYLE = Build.PL
DEPENDS           = perl/perl-Carp-Clan
BUILDDEPS         = perl/perl-Test-Exception

include ../../perl/perl/perl-module.mk
