#ifndef PLAYBACKSTATE_H
#define	PLAYBACKSTATE_H

typedef enum {
	PLAYBACKSTATE_PLAY = 0,
	PLAYBACKSTATE_PAUSE = 1,
	PLAYBACKSTATE_STOP = 2,
	PLAYBACKSTATE_FF = 3,
	PLAYBACKSTATE_RW = 4
} PlaybackState;

#endif

