GARNAME           = perl-Carp-Clan
GARVERSION        = 6.04
MASTER_SITES      = http://search.cpan.org/CPAN/authors/id/S/ST/STBEY/
DEPENDS           = 
BUILDDEPS         = perl/perl-Test-Exception

include ../../perl/perl/perl-module.mk
