
GARNAME      = bootfiles-h6.tanix_tx6
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = h6
mm_U-BOOT_BOARD_TYPE      = board-h6.tanix_tx6
mm_U-BOOT_BOARD_DEFCONFIG = tanix_tx6_defconfig
CRUST_CONFIG              = tanix_tx6_defconfig

include ../bootloader/install-board-bootloader-aw.mk

