
GARNAME             = perl-LWP-Protocol-https
GARVERSION          = 6.14
MASTER_SITES        = https://search.cpan.org/CPAN/authors/id/O/OA/OALDERS/
DEPENDS             = perl/perl perl/perl-IO-Socket-SSL perl/perl-Net-HTTP perl/perl-libwww-perl

include ../../perl/perl/perl-module.mk
