#!ipxe

# Version of MiniMyth2.
# Default build system creates distro top dir like [nfs-arm64-minimyth2-master-15.2.0.r342]
set mm2_version master-latest

# Device DTB
set device_dtb qcom/qcs6490-radxa-dragon-q6a.dtb

# Extra kernel parameters speciffic to given SoC
set kernel_extra_para console=ttyMSM0,115200n8 earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 clk_ignore_unused pd_ignore_unused debug

# IP address with tftp/http servers
set server_ip 192.168.1.254








# set nfs_top_dir nfs-arm64-minimyth2-${mm2_version}
set nfs_top_dir mm2-nfs-networkboot-latest
# set ram_top_dir ram-arm64-minimyth2-${mm2_version}
set ram_top_dir mm2-ram-networkboot-latest

set http_base http://${server_ip}/minimyth2
set menu-timeout 5000
set menu-default NFS

isset ${ip} || dhcp

:start
menu iPXE Boot Menu - Please select type of boot mode
item --gap --             ------ MiniMyth2 Boot ------
item --key n nfs          (n) NFS RootFS
item --key r ram          (r) RAM disk based RootFS
item --key l Local        (l) Local Boot (from local storage)
item --gap --             ---------- Tools -----------
item shell                Console iPXE
item reboot               Reboot
choose --timeout ${menu-timeout} --default ${menu-default} target && goto ${target}

:nfs
echo Booting with NFS root FS ...
fdt    ${http_base}/${nfs_top_dir}/boot/dtbs/${device_dtb}
kernel ${http_base}/${nfs_top_dir}/boot/Image root=/dev/nfs nfsroot=${server_ip}:/var/tftpboot/PXEclient/${nfs_top_dir}/rootfs,v3,ro ro ip=dhcp ${kernel_extra_para}
boot

:ram
echo Booting with RAM disk based root FS ...
fdt    ${http_base}/${ram_top_dir}/boot/dtbs/${device_dtb}
kernel ${http_base}/${ram_top_dir}/boot/Image ro root=/dev/ram0 initrd=rootfs ramdisk_size=512000 ${kernel_extra_para}
initrd ${http_base}/${ram_top_dir}/rootfs
boot

:local
echo Booting from local storage ...
exit

:shell
echo Type 'exit' for return menu ...
shell
goto start

:reboot
reboot
