
# OSD UI localization file. 
# This file is processed interrnally by Minimyth2 so some chars are reserved for
# processing and can't be used in this file. Those hars are: 
# plus char "+"
# backslash char "\"


#---- OSD messaging in Maintenance
# /usr/bin/mm_manage v2021.02.24

restart_mythfrontend_str			="Restartuję proces Mythfrontend..."
restart_xserver_str				="Restartuję X-Serwer..."
restart_this_frontend_str			="Restartuję Frontend..."
reload_this_system_str				="Nowe oprogramowanie wymaga restaru. Restartuję Frontend..."
shutdown_this_frontend_str			="Wyłączam Ten System..."
restart_backend_str				="Restartuję MythTV Backend..."
restart_server_str				="Restartuję Centralny Serwer..."
save_themecache_str				="Zapisuję cache skórki..."
save_themecache_ok_str				="Cache skórki zapisano pomyślnie !"
save_cookiejar_str				="Zapisuję ciasteczka WEB..."
save_cookiejar_ok_str				="Ciasteczka WEB zapisano pomyślnie !"
save_game_str					="Zapisuję ustawienia gier..."
save_game_ok_str				="Ustawienia gier zapisano pomyślnie !"
restore_game_str				="Odtwarzam ustawienia gier..."
restore_game_ok_str				="Ustawienia gier odtworzono pomyślnie !"
reload_voip_config_str				="Przeładowuję podsystem VoIP..."
reload_voip_config_ok_str			="Podsystem VoIP przeładowany pomyślnie !"
redownload_theme_str				="Zciągam i instaluję skórkę..."
redownload_theme_ok_str				="Skórka zciągnięta pomyślnie !"
checking_for_system_updates_str			="Sprawdzam dostępność aktualizacji..."
system_updates_str				="Aktualizacja Systemu"
packages_were_updated_str			=" pakiet(y) został zaktualizowany :-)"
checking_in_background_str			="Sprawdzam aktualizacje w tle ..."
checking_for_system_updates_str			="Sprawdzam aktualizacje ..."
installing_updates_in_background_str		="Instaluję aktualizacje w tle ..."
installing_system_updates_str			="Instaluję systemowe aktualizacje ..."
there_is_no_any_updates_for_yours_system_str	="System jest w pełni aktualny ..."
new_ir_remote_connected_str			="Dołączono/odłączono zdalne serowanie ..."
new_input_device_added_str			="Dołączono/odłączono myszkę/klawiaturę ..."
new_storage_device_connected_str		="Dołączono dysk ..."
storage_device_removed_str			="OdłączonoStorage dysk ..."
error_str					="Wystąpił błąd: "


#---- OSD notifications about new. on-line version is avaliable
# /usr/bin/mm_notify_updates v2021.02.24

updates_detected_str			="Jest nowa versja MiniMyth2 !"
please_update_system_str		="Możesz dokonać aktualizacji ..."

#---- OSD messaging in Maintenance/Updates
# /usr/bin/mm_do_online_update v2021.02.24

system_is_already_up_to_date_str	="System is already up-to-date :-)"
on_line_updates_str			="Aktualizacja On-line"
there_is_no_any_updates_str		="System jest w pełni aktualny :-)"
files_were_updated_str			=" plik(i) zostały zaktualizowane :-)"
update_will_effect_after_reboot_str	="Aktualizacja zadziała po restarcie !"
files_to_update_str			=" plik(ów) jest do aktualizacji !"
something_went_wrong_str		="Oj, coś poszło nie tak :-("

#---- OSD messaging in test LAN speed
# /usr/bin/mm_test_network_speed 02.07.2021

test_network_speed_str			="Test prędkości LAN/WiFi"
measured_network_speed_str		="Aktualna Prędkość: "
error_testing_network_speed_str>	="Błąd połączenia z demonem netperf!"

#---- OSD messaging in mythtv_cache_prunner
# /usr/bin/mm_mythtv_cache_prunner 15.09.2021

pruning_mythtv_cache_str		="Zarządzanie MythTV Cache"
mythtv_cache_occupation_str		="Bieżący rozmiar cache: "
mythtv_cache_prunning_str		="Oczyszczenie do "

#--show OSD--

server_title_str		= "Serwer";
frontend_title_str		= "Frontend";
process_str			= ": Proces ";
memory_usage_str		= "Pamięć: ";
memory_used_str			= "Pamięć: ";
hardware_str			= ": Sprzęt ";
uptime_str			= "Czas Pracy: ";
cpu_freq_str			= "Zegary: ";
cpu_load_str			= "Obciążenie: ";
starts_str			= "";
ends_str			= " - ";
recorder_id_str			= " | Tuner:  ";
next_recordings_str		= "Przyszłe Nagrania";
tuners_str			= "Tunery";
all_tuners_idle_str		= "Wszystkie tunery są wolne...";
total_str			= "Całkowity ";
till_end_str			= " Do końca ";




#--new mail notify--

new_mail_str			= "Nowy E-Mail...";
accout_str			= "";
mails_str			= " nowych wiadomości...";


