
GARNAME      = bootfiles-t527.orangepi_4a
GARVERSION   = 2026-09-05
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = a523
mm_U-BOOT_BOARD_TYPE      = board-t527.orangepi_4a
mm_U-BOOT_BOARD_DEFCONFIG = orangepi_4a_defconfig

include ../bootloader/install-board-bootloader-aw.mk
