GARNAME      = perl-SOAP-Lite
GARVERSION   = 1.27
MASTER_SITES = https://search.cpan.org/CPAN/authors/id/P/PH/PHRED/
DEPENDS      = perl/perl-libwww-perl perl/perl-XML-Parser perl/perl-Class-Inspector

include ../../perl/perl/perl-module.mk

CONFIGURE_ENV := echo Y | $(CONFIGURE_ENV)
