GARNAME      = perl-SOAP-Lite
GARVERSION   = 0.69
MASTER_SITES = http://www.cpan.org/authors/id/B/BY/BYRNE/
DEPENDS      = perl/perl-libwww-perl perl/perl-XML-Parser

include ../../perl/perl/perl-module.mk

CONFIGURE_ENV := echo Y | $(CONFIGURE_ENV)
