GARNAME        = perl-XML-Parser
GARVERSION     = 2.36
MASTER_SITES   = http://www.cpan.org/authors/id/M/MS/MSERGEANT/
DEPENDS        = lib/expat perl/perl-libwww-perl
PERL_MODULE_SO = true

include ../../perl/perl/perl-module.mk
