GARNAME             = perl-WWW-Curl
GARVERSION          = 4.15
MASTER_SITES        = http://www.cpan.org/authors/id/S/SZ/SZBALINT/
PERL_MODULE_PATCHES = gar.patch.gar
PERL_MODULE_SO      = true
DEPENDS             = net/curl

include ../../perl/perl/perl-module.mk
