GARNAME      = perl-Exception-Class
GARVERSION   = 1.25
MASTER_SITES = https://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-Class-Data-Inheritable

include ../../perl/perl/perl-module.mk
