
GARNAME             = perl-Config-General
GARVERSION          = 2.63
MASTER_SITES        = https://cpan.metacpan.org/authors/id/T/TL/TLINDEN/
DEPENDS             = perl/perl

include ../../perl/perl/perl-module.mk
