#!/bin/bash

build() {
    local applet

    add_binary /usr/lib/initcpio/busybox /bin/busybox

    for applet in $(/usr/lib/initcpio/busybox --list); do
        add_symlink "/usr/bin/$applet" busybox
    done

    # add kmod with applet symlinks
    add_binary /bin/kmod
    for applet in {dep,ins,rm,ls}mod mod{probe,info}; do
        add_symlink "/usr/bin/$applet" kmod
    done

    add_binary /bin/blkid
    add_binary /bin/mount
    add_binary /bin/switch_root

    add_file "/usr/lib/initcpio/init_functions" "/init_functions"
    add_file "/usr/lib/initcpio/init" "/init"
}

help() {
    cat <<HELPEOF
This hook provides crucial runtime necessities for booting. DO NOT
remove this hook unless you know what you're doing.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
