
[options]
Architecture = aarch64
IgnorePkg    = linux-aarch64 linux-aarch64-headers linux-aarch64-api-headers linux-headers linux-api-headers linux-firmware
CheckSpace

# [miniarch]
# Server = https://github.com/warpme/miniarch/raw/refs/heads/master

[core]
Server = http://mirror.archlinuxarm.org/$arch/$repo

[extra]
Server = http://mirror.archlinuxarm.org/$arch/$repo
