
GARNAME      = bootfiles-rk3568.rock3-b
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

SOC_TYPE                  = rk3568
mm_U-BOOT_BOARD_TYPE      = board-rk3568.rock3-b
mm_U-BOOT_BOARD_DEFCONFIG = rock-3b-rk3568_defconfig

include ../bootloader/install-board-bootloader-rk.mk
