GARNAME           = perl-HTML-Tree
GARVERSION        = 5.07
MASTER_SITES      = https://search.cpan.org/CPAN/authors/id/K/KE/KENTNL/
PERL_MODULE_STYLE = Build.PL
DEPENDS           = perl/perl-HTML-Parser perl/perl-HTML-Tagset perl/perl-Module-Build perl/perl-Test-Fatal

include ../../perl/perl/perl-module.mk
