
GARNAME             = perl-Config-Simple
GARVERSION          = 4.58
MASTER_SITES        = https://cpan.metacpan.org/authors/id/S/SH/SHERZODR/
DEPENDS             = perl/perl

include ../../perl/perl/perl-module.mk
