
GARNAME      = bootfiles-rk3588s.orangepi_5_pro
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf

SOC_TYPE                  = rk3588s
mm_U-BOOT_BOARD_TYPE      = board-rk3588s.orangepi_5_pro
mm_U-BOOT_BOARD_DEFCONFIG = orangepi-5-rk3588s_defconfig

include ../bootloader/install-board-bootloader-rk.mk
