#!/bin/sh

# this script is called at very erlay boot from /etc/rc.d/init.d/modules_manual_early.
# it is useful for any actions on system before init scripts will be executed.
# name of script should be equal to part after last coma in dt <compatile> string.
# i.e. is compatible is <raspberrypi,5-model-b.brcm,bcm2712>, filename should be <bcm2712>
# you can determine required scrpit name by looking for value of variable MM_HW_DEVICE_COMPATIBLE
# in /etc/conf.d/hwdevice file under running system.



# generating custom eglfs config file as it looks like on rpi5 qt automatic selection 
# of drm device wrongly selects v3d (gpu) device insrtead of kms (vc4) device

cat > /home/minimyth/.mythtv/eglfs-config.json <<EOF
{
    "device": "/dev/dri/card0"
}
EOF
