
GARNAME      = bootfiles-rk3576.rock_4d
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf

SOC_TYPE                  = rk3576
mm_U-BOOT_BOARD_TYPE      = board-rk3576.rock_4d
mm_U-BOOT_BOARD_DEFCONFIG = rock4d-rk3576_defconfig

include ../bootloader/install-board-bootloader-rk.mk
