
GARNAME      = bootfiles-rk3588s.edge2
GARVERSION   = 2026-02-12
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf

SOC_TYPE                  = rk3588s
mm_U-BOOT_BOARD_TYPE      = board-rk3588s.edge2
mm_U-BOOT_BOARD_DEFCONFIG = khadas-edge2-rk3588s_defconfig

include ../bootloader/install-board-bootloader-rk.mk
