
GARNAME      = bootfiles-rk3588.rock5-b
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

SOC_TYPE                  = rk3588
mm_U-BOOT_BOARD_TYPE      = board-rk3588.rock5-b
mm_U-BOOT_BOARD_DEFCONFIG = rock5b-rk3588_defconfig

include ../bootloader/install-board-bootloader-rk.mk
