
GARNAME             = perl-Net-SSLeay
GARVERSION          = 1.94
MASTER_SITES        = https://cpan.metacpan.org/authors/id/C/CH/CHRISN/
DEPENDS             = lib/openssl

include ../../perl/perl/perl-module.mk

CONFIGURE_ENV := echo Y | $(CONFIGURE_ENV)
