GARNAME           = perl-Params-ValidationCompiler
GARVERSION        = 0.30
MASTER_SITES      = https://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/
DEPENDS           = perl/perl-Exception-Class

include ../../perl/perl/perl-module.mk
