GARNAME           = perl-IO-Socket-INET6
GARVERSION        = 2.72
MASTER_SITES      = https://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF/
#DEPENDS           = perl/perl-Socket6

include ../../perl/perl/perl-module.mk
