
GARNAME      = bootfiles-a527.cubie_a5e
GARVERSION   = 2026-09-05
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = a523
mm_U-BOOT_BOARD_TYPE      = board-a527.cubie_a5e
mm_U-BOOT_BOARD_DEFCONFIG = radxa-cubie-a5e_defconfig

include ../bootloader/install-board-bootloader-aw.mk

