GARNAME      = perl-XML-Catalog
GARVERSION   = 1.03
MASTER_SITES = http://search.mcpan.org/CPAN/authors/id/J/JF/JFEARN/
DEPENDS      = perl/perl-libwww-perl perl/perl-URI perl/perl-XML-Parser

include ../../perl/perl/perl-module.mk
