GARNAME           = perl-B-Hooks-EndOfScope
GARVERSION        = 0.26
MASTER_SITES      = https://cpan.metacpan.org/authors/id/E/ET/ETHER/
DEPENDS           = perl/perl-Module-Implementation perl/perl-Module-Runtime perl/perl-Sub-Exporter perl/perl-Sub-Exporter-Progressive perl/perl-Try-Tiny perl/perl-Variable-Magic

include ../../perl/perl/perl-module.mk
