GARNAME           = perl-Capture-Tiny
GARVERSION        = 0.48
MASTER_SITES      = https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/
DEPENDS           = 
BUILDDEPS         = perl/perl

include ../../perl/perl/perl-module.mk
