
GARNAME      = bootfiles-h6.eachlink_mini
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = h6
mm_U-BOOT_BOARD_TYPE      = board-h6.eachlink_mini
mm_U-BOOT_BOARD_DEFCONFIG = eachlink_h6_mini_defconfig
CRUST_CONFIG              = tanix_tx6_defconfig

include ../bootloader/install-board-bootloader-aw.mk

