GARNAME           = perl-File-ShareDir-Install
GARVERSION        = 0.13
MASTER_SITES      = https://cpan.org/modules/by-module/File/
DEPENDS           = perl/perl-Class-Inspector

include ../../perl/perl/perl-module.mk
