LABEL MiniMyth2

  LINUX /Image
  FDT /dtbs/amlogic/meson-gxm-beelink-gt1.dtb

  # Cmd line to production-like quiet boot
  # APPEND root=/dev/mmcblk0p2 rw rootwait console=ttyAML0,115200n8 console=tty0 logo.nologo vt.cur_default=1
  # Cmd line to debug kernel boot
  APPEND root=/dev/mmcblk0p2 rw rootwait console=ttyAML0,115200n8 console=tty0 debug MM_DEBUG="yes"
