
GARNAME      = bootfiles-h313-x96-q-v5.1
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = h313
mm_U-BOOT_BOARD_TYPE      = board-h313.x96_q_v5.1
mm_U-BOOT_BOARD_DEFCONFIG = x96_q_ddr3_v5.1_defconfig

include ../bootloader/install-board-bootloader-aw.mk

