
GARNAME      = bootfiles-rk3588.orange5-plus
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

SOC_TYPE             = rk3588
mm_U-BOOT_BOARD_TYPE = board-rk3588.orangepi_5_plus

# uncomment and set this for dedicated defconfig.
# if commented out, generic defconfig 'generic-<soc>_defconfig' will be used...
# mm_U-BOOT_BOARD_DEFCONFIG =

include ../bootloader/install-board-bootloader-rk.mk
