
GARNAME      = bootfiles-rk3566.quartz64-b
GARVERSION   = 2025-06-26
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

SOC_TYPE                  = rk3566
mm_U-BOOT_BOARD_TYPE      = board-rk3566.quartz64-b
mm_U-BOOT_BOARD_DEFCONFIG = quartz64-b-rk3566_defconfig

include ../bootloader/install-board-bootloader-rk.mk
