
GARNAME      = bootfiles-a733.cubie_a7a
GARVERSION   = 2026-09-15
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf       \
               extlinux.conf       \

SOC_TYPE                  = a733
mm_U-BOOT_BOARD_TYPE      = board-a733.cubie_a7a
mm_U-BOOT_BOARD_DEFCONFIG = radxa-cubie-a7a_defconfig

include ../bootloader/install-board-bootloader-a733.mk

