
GARNAME      = bootfiles-board-s905y4.vim1s
GARVERSION   = 2026-10-04
CATEGORIES   = bootloaders
MASTER_SITES = 
DISTFILES    = \
               minimyth.conf \
               extlinux.conf \

export SOC_TYPE                  = s4
export mm_U-BOOT_BOARD_TYPE      = board-s905y4.vim1s
export mm_U-BOOT_BOARD_DEFCONFIG = khadas-vim1s_defconfig
export FIP_BOARD                 = khadas-vim1s

include ../bootloader/install-board-bootloader-aml.mk
