GARNAME             = perl-Socket6
GARVERSION          = 0.29
MASTER_SITES        = https://search.cpan.org/CPAN/authors/id/U/UM/UMEMOTO/
PERL_MODULE_PATCHES = fix-cross-compile.patch

include ../../perl/perl/perl-module.mk
