GARNAME      = perl-DateTime-Format-Strptime
GARVERSION   = 1.75
MASTER_SITES = http://www.cpan.org/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-DateTime perl/perl-DateTime-Locale perl/perl-DateTime-TimeZone perl/perl-Params-Validate

include ../../perl/perl/perl-module.mk
